# Generated by Django 5.0.7 on 2025-08-20 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('game', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('daily_start_time', models.TimeField()),
                ('daily_hours', models.PositiveIntegerField(default=2)),
                ('entry_fee', models.PositiveIntegerField()),
                ('max_teams', models.PositiveIntegerField()),
                ('max_players_per_team', models.PositiveIntegerField()),
                ('max_overs', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
