# Generated by Django 5.0.7 on 2025-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
